### ISSUE TITLE
Oembed in WYSIWYG 

### ISSUE THREAD

**Issue by yumyo** [mgibbs189/custom-field-suite#264]
This has been asked before and marked as solved here [http://customfieldsuite.com/forums/questions/1714/auto-embed-youtube-links-with-cfs-wysiwyg-object](http://customfieldsuite.com/forums/questions/1714/auto-embed-youtube-links-with-cfs-wysiwyg-object) however even with the "default" setting in place the link keeps being converted to text and no embed shows up. 

Embed working in regular posts (same video url). I'm using CFS on a cpt. Also the embed shows up properly in the admin area but fails on the frontend. 

The code used to render the field is `echo CFS()->get('prod_content');`

WP version 4.2.1
CFS version 2.4.2

**Comment by mgibbs189** [comment]
Have you tried manually triggering oembed?

```php
echo $GLOBALS['wp_embed']->autoembed(  CFS()->get( 'prod_content' ) );
```

**Comment by sebvandijk** [comment]
Hi, 

I have this same issue. Tried the above code and the field is on default formatting. In the post admin the embed is showing perfectly but on the front-end I just get the url (Instagram)

Are there any other possibilities to look at? 

Thanks

**Comment by robneu** [comment]
This issue still exists. For some reason, no matter how you try to trigger the embeds on the front end, it fails. 

If I change the field type to `textarea`, everything will work normally on the front end if you apply the appropriate filters. On the wysiwyg field, it refuses to work even if you set formatting to `none` on the field formattion options.

I've done a little initial digging into CFS for an answer, but so far I'm not seeing where the problem is.

**Comment by chrisvanpatten** [comment]
Can confirm that the fix above doesn't work. I have an idea (filters being called in the wrong order) but I'm going to continue debugging.

**Comment by chrisvanpatten** [comment]
Okay, it's a pretty understandable problem (although I'm not sure of a good fix).

Basically, the content is being saved with `<p>` tags already applied. That means that your YouTube link row becomes `<p>http://youtube.com/link-here</p>`, which the oEmbed parser doesn't catch (because of the `<p>` tag).

The simple, quick fix is to wrap your oEmbed in `[embed]` shortcodes, e.g. `[embed]http://youtube.com/[/embed]`.

The long answer is that I think the wpautop TinyMCE plugin is being activated incorrectly, which is causing this behaviour. I'm going to keep poking around.

**Comment by chrisvanpatten** [comment]
@mgibbs189 I think I found the problem, but I'm going to email it to you privately so people don't get the temptation to edit core files in the plugin and break things further.

**Comment by mgibbs189** [comment]
@chrisvanpatten I can't remember exactly why, but I set `wpautop` to false (before initializing the editor) to fix a formatting issue. I have no idea if it's still applicable.

https://github.com/mgibbs189/custom-field-suite/blob/master/includes/fields/wysiwyg.php#L137-L143

**Comment by jchristopher** [comment]
I remember hitting that issue with one of my plugins, IIRC it was losing newlines if it wasn't set to `false` but I haven't revisited the issue since, probably in 2 years or so.

**Comment by chrisvanpatten** [comment]
@jchristopher I actually saw your code while searching around for more info haha. 

My guess is that in the intervening time, something in TinyMCE changed. I'll try to go back and see exactly when it broke.

**Comment by jchristopher** [comment]
Haha figures! Yeah I'm 99% sure it was because the newlines got lost when trying to restore the content, but maybe that's because it's being stored improperly in the first place?

**Comment by chrisvanpatten** [comment]
I am ON THE CASE 🔎

**Comment by mgibbs189** [comment]
Roger that!

**Comment by chrisvanpatten** [comment]
Planning to revisit this in the next few weeks… 🚀
