### ISSUE TITLE
CFS does not include data in posts that are retrieved by WP Rest API

### ISSUE THREAD

**Issue by OJayRobinson** [mgibbs189/custom-field-suite#266]
I used CFS to add fields to all posts, but the field data does not show when I retrieve post data through the [WP Rest API](http://wp-api.org/) using [/posts](http://wp-api.org/#posts_retrieve-posts).  It would be nice if this was the default behavior.

I cannot find a way to do this in the documentation, and am not sure if it is possible.  It feels like I just need to put a CFS()->get call in the right place.

**Comment by mgibbs189** [comment]
We'll revisit this ticket once the WP-API makes it into core. Closing in the meantime.

**Comment by mattbanks** [comment]
With the infrastructure part in Core, I wanted to bring this up. I haven't had a chance to look at the code base (it's been a while), but can `register_api_field()` be called when the fields are created? It would need to be passed getter and setter callbacks for retrieving and updating the field. I'll try to take a look at this soon, because I'd love to contribute! If someone can get to it before me, please go ahead :)

**Comment by mgibbs189** [comment]
@mattbanks I know very little about the REST API yet, but I'm all ears :)

**Comment by mgibbs189** [comment]
Created a new issue stub: #301
