### ISSUE TITLE
Use admin_notices to highlight errors before saving

### ISSUE THREAD

**Issue by jackmcconnell** [mgibbs189/custom-field-suite#290]
So currently, if a field that is required is hidden behind a tab and the user clicks Publish / Update, nothing will happen. I propose using the admin_notices function to highlight issues to the user so that they can correct them before throwing their keyboard out of the window because of a misunderstanding.

**Comment by mgibbs189** [comment]
:+1: agreed

**Comment by chrisvanpatten** [comment]
FWIW, I hit this problem as well. Happens if a loop row is closed as well. I won't have time to look for a few weeks, but I suspect it wouldn't be _too_ bad to fix. Would probably just need to detect if the validation error is happening in a non-active tab or closed loop row, and have the tab/row opened via JS. Adding the admin notice could be a secondary measure as well.
