### ISSUE TITLE
REST API Integration

### ISSUE THREAD

**Issue by mgibbs189** [mgibbs189/custom-field-suite#301]

**Comment by mattbanks** [comment]
It was just announced that a breaking change in REST API beta 10 will change `register_api_field()` to `register_rest_field()`, so I'll have to dig more into that once it's released to see what changes are coming down with that. There are more plans to introduce breaking changes until the endpoints get fully integrated into Core in (hopefully) January/February 2016.

The gist of things is that the fields all need to get registered with the API with get and update callbacks for how to retrieve and process the field, which can theoretically use `CFS()->get()` and `CFS->save()` (or the respective direct calls in the API), with all of the proper data passed through for each field type and post ID.

**Comment by mattbanks** [comment]
Expanding upon my last comment, I did a little digging and got some more info.

I think the issue that will come into play is checking the placement rules for the field group. With `register_rest_field()`, you need to pass the post object that the field is associated with in order to have it processed (see [documentation](http://v2.wp-api.org/extending/modifying/)). Doing it for post types shouldn't too bad, since [that can be done in the Save Rules section of the field group](https://github.com/mgibbs189/custom-field-suite/blob/master/includes/field_group.php#L266-L268), but getting the field only associated with particular post ID's might be iffy. I don't believe that `register_rest_field()` currently offers anything for associating a custom field with individual post IDs at this point, so it might be an all or nothing thing for showing fields in the REST API for a particular post type. That might not be a huge deal, since the fields will be null if they aren't displayed and editable in the admin.

**Comment by chrisvanpatten** [comment]
I want to add to this discussion a bit.

I've already used CFS fields with the REST API for a few client projects, with a lot of success.

However, I don't think a generic "CFS fields at core endpoints" feature should be included in CFS core, and certainly should not be enabled by default. This may be stating the obvious, but I thought it'd be good to get in writing.

There are a few reasons for this:

1. Some field data might be private, or not intended to be publicly accessible
2. Field data sometimes needs to be manipulated to be useful

Extending core endpoints is *really dang easy* with the REST API. If you're using CFS, you are probably comfortable with the level of skillz required to add your CFS data to an endpoint. Once the core endpoints are in place, it'd make sense to include an example of how to add them with the built-in filters.

In terms of writing CFS data through the API…

I can understand the utility there, but I'm still not sure it should be built into CFS core. Perhaps it would be more useful to provide some generic, easy-to-understand helper methods for updating field content (and if they're already there, make them more visible in documentation) and some examples for how to use them in connection with the REST API (again, once the core endpoints are in place).

**Comment by mgibbs189** [comment]
@chrisvanpatten Good points.

My REST API experience is limited, but I agree that injecting CFS into **core** endpoints probably isn't the way to go. Instead, maybe an add-on or something that provides CFS-specific endpoints.

**Comment by voltronik** [comment]
I'm looking for REST API integration too. 
@chrisvanpatten Can you explain what you did to read and write to CFS using the WP REST API?

**Comment by chrisvanpatten** [comment]
I haven't done any writing to the API, but reading is super easy.

```php
<?php
add_action( 'rest_api_init', 'slug_register_starship' );
function slug_register_starship() {
    register_rest_field( 'post',
        'starship_name',
        array(
            'get_callback'    => 'slug_get_starship',
            'update_callback' => null,
            'schema'          => null,
        )
    );
}

/**
 * Get the value of the "starship" field
 *
 * @param array $object Details of current post.
 * @param string $field_name Name of field.
 * @param WP_REST_Request $request Current request
 *
 * @return string
 */
function slug_get_starship( $object, $field_name, $request ) {
    return CFS()->get( $field_name, $object[ 'id' ] );
}
```

**Comment by voltronik** [comment]
@chrisvanpatten Thanks Chris. So you're basically adding the contents of the CFS field as a 'rest field'. Is that right? 

How would one go about writing to that field? Is there any documentation on this?
