### ISSUE TITLE
Saving preset configs

### ISSUE THREAD

**Issue by amindiary** [mgibbs189/custom-field-suite#338]
Hi, Is there any way to save all configurations (fields,...) in a php file and integrate it with theme?
I mean integration with a theme without need installing the plugin separately. 
- Putting plugin on theme (OK)
- Activating and hiding from admin menu (OK)
- Loading predefined configs of fields (?)

**Comment by chrisvanpatten** [comment]
Integrating the plugin with your theme directly is a terrible idea; primarily because it keeps users from future security updates. It's a disaster waiting to happen.

I'd strongly encourage you to use something like [TGMPA](http://tgmpluginactivation.com) to require that your users install the plugin, rather than bundling the files directly.

Then, you can use [something like this to automatically install your fields](https://github.com/vanpattenmedia/cfs-require-import).

**Comment by amindiary** [comment]
Thank you for that useful reply :)
